// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {repository} from '../models';
import {model} from '../models';
import {service} from '../models';

export function BackfillActorAvatars(arg1:string):Promise<main.ActorAvatarBackfillResult>;

export function BatchAddTag(arg1:Array<string>,arg2:string):Promise<void>;

export function BatchRemoveTag(arg1:Array<string>,arg2:string):Promise<void>;

export function BatchSetMyRating(arg1:Array<string>,arg2:number):Promise<void>;

export function CancelLibraryScan(arg1:string):Promise<void>;

export function CancelScan(arg1:string):Promise<void>;

export function CleanOrphanedMediaAssociations():Promise<repository.OrphanedMediaCleanupResult>;

export function ClearActorAvatar(arg1:string):Promise<void>;

export function CountTaggedMedia():Promise<number>;

export function CreateLibrary(arg1:model.Library):Promise<model.Library>;

export function CreateMyTag(arg1:string,arg2:string):Promise<model.Tag>;

export function CycleActorAvatar(arg1:string):Promise<main.ActorAvatarCycleResult>;

export function DeleteLibrary(arg1:string):Promise<main.DeleteLibraryResult>;

export function DeleteMedia(arg1:string):Promise<void>;

export function DeleteMyTag(arg1:string):Promise<void>;

export function DownloadFFmpeg():Promise<void>;

export function GetActorStats(arg1:string):Promise<Array<main.StatsItem>>;

export function GetDesktopSettings():Promise<main.DesktopSettings>;

export function GetDetailRecommendations(arg1:string,arg2:number):Promise<service.DetailRecommendationResponse>;

export function GetDirectoryStats(arg1:string):Promise<Array<main.StatsItem>>;

export function GetFFmpegStatus():Promise<main.FFmpegStatus>;

export function GetFilterFacets(arg1:string,arg2:string,arg3:string,arg4:string,arg5:main.UserFilter):Promise<main.FilterFacets>;

export function GetGenreStats(arg1:string):Promise<Array<main.StatsItem>>;

export function GetLastScanFailure(arg1:string):Promise<main.ScanTaskInfo>;

export function GetLastScanTask(arg1:string):Promise<main.ScanTaskInfo>;

export function GetLibraries():Promise<Array<model.Library>>;

export function GetMediaDetail(arg1:string):Promise<model.Media>;

export function GetMediaDetailBundle(arg1:string):Promise<main.MediaDetailBundle>;

export function GetMediaFiles(arg1:string):Promise<Array<string>>;

export function GetMediaList(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<any>;

export function GetMediaListFiltered(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:main.UserFilter):Promise<any>;

export function GetMediaPreviews(arg1:string):Promise<Array<string>>;

export function GetMyRating(arg1:string):Promise<number>;

export function GetNFOEditorData(arg1:string):Promise<service.NFOEditorData>;

export function GetPosterEditorState(arg1:string):Promise<main.PosterEditorState>;

export function GetSeriesStats(arg1:string):Promise<Array<main.StatsItem>>;

export function GetThumbnailFailure(arg1:string):Promise<service.ThumbnailTaskEventData>;

export function ListMyTags():Promise<Array<main.TagWithCount>>;

export function MergeMyTags(arg1:string,arg2:string):Promise<void>;

export function MoveMyTag(arg1:string,arg2:string):Promise<void>;

export function OpenMediaFolder(arg1:string):Promise<void>;

export function OpenNFO(arg1:string):Promise<void>;

export function PlayMedia(arg1:string,arg2:string):Promise<void>;

export function PlayRandomLibraryMedia(arg1:string):Promise<string>;

export function PlayWithExternalPlayer(arg1:string):Promise<void>;

export function RenameMyTag(arg1:string,arg2:string):Promise<void>;

export function RestartApp():Promise<void>;

export function RestartMedia(arg1:string,arg2:string):Promise<void>;

export function RestoreMediaPoster(arg1:string):Promise<model.Media>;

export function RetryFailedScan(arg1:string):Promise<main.ScanTaskInfo>;

export function RetryThumbnailTask(arg1:string):Promise<service.ThumbnailTaskEventData>;

export function SaveMediaPoster(arg1:main.SaveMediaPosterRequest):Promise<model.Media>;

export function SaveNFOEditorData(arg1:string,arg2:service.NFOEditorData):Promise<void>;

export function ScanLibrary(arg1:string):Promise<main.ScanTaskInfo>;

export function ScanLibraryWithMode(arg1:string,arg2:string):Promise<main.ScanTaskInfo>;

export function SelectActorAvatarFile():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectPosterImageFile():Promise<string>;

export function SelectProgram():Promise<string>;

export function SetActorAvatarFromFile(arg1:string,arg2:string):Promise<string>;

export function SetActorAvatarFromURL(arg1:string,arg2:string):Promise<string>;

export function SetMediaTags(arg1:string,arg2:Array<string>):Promise<void>;

export function SetMyRating(arg1:string,arg2:number):Promise<void>;

export function ToggleFavorite(arg1:string):Promise<void>;

export function ToggleWatched(arg1:string):Promise<void>;

export function UpdateDesktopSettings(arg1:main.DesktopSettings):Promise<void>;

export function UpdateLibrary(arg1:model.Library):Promise<void>;
