// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackfillActorAvatars(arg1) {
  return window['go']['main']['App']['BackfillActorAvatars'](arg1);
}

export function BatchAddTag(arg1, arg2) {
  return window['go']['main']['App']['BatchAddTag'](arg1, arg2);
}

export function BatchRemoveTag(arg1, arg2) {
  return window['go']['main']['App']['BatchRemoveTag'](arg1, arg2);
}

export function BatchSetMyRating(arg1, arg2) {
  return window['go']['main']['App']['BatchSetMyRating'](arg1, arg2);
}

export function CancelLibraryScan(arg1) {
  return window['go']['main']['App']['CancelLibraryScan'](arg1);
}

export function CancelScan(arg1) {
  return window['go']['main']['App']['CancelScan'](arg1);
}

export function CleanOrphanedMediaAssociations() {
  return window['go']['main']['App']['CleanOrphanedMediaAssociations']();
}

export function ClearActorAvatar(arg1) {
  return window['go']['main']['App']['ClearActorAvatar'](arg1);
}

export function CountTaggedMedia() {
  return window['go']['main']['App']['CountTaggedMedia']();
}

export function CreateLibrary(arg1) {
  return window['go']['main']['App']['CreateLibrary'](arg1);
}

export function CreateMyTag(arg1, arg2) {
  return window['go']['main']['App']['CreateMyTag'](arg1, arg2);
}

export function CycleActorAvatar(arg1) {
  return window['go']['main']['App']['CycleActorAvatar'](arg1);
}

export function DeleteLibrary(arg1) {
  return window['go']['main']['App']['DeleteLibrary'](arg1);
}

export function DeleteMedia(arg1) {
  return window['go']['main']['App']['DeleteMedia'](arg1);
}

export function DeleteMyTag(arg1) {
  return window['go']['main']['App']['DeleteMyTag'](arg1);
}

export function DownloadFFmpeg() {
  return window['go']['main']['App']['DownloadFFmpeg']();
}

export function GetActorStats(arg1) {
  return window['go']['main']['App']['GetActorStats'](arg1);
}

export function GetDesktopSettings() {
  return window['go']['main']['App']['GetDesktopSettings']();
}

export function GetDetailRecommendations(arg1, arg2) {
  return window['go']['main']['App']['GetDetailRecommendations'](arg1, arg2);
}

export function GetDirectoryStats(arg1) {
  return window['go']['main']['App']['GetDirectoryStats'](arg1);
}

export function GetFFmpegStatus() {
  return window['go']['main']['App']['GetFFmpegStatus']();
}

export function GetFilterFacets(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetFilterFacets'](arg1, arg2, arg3, arg4, arg5);
}

export function GetGenreStats(arg1) {
  return window['go']['main']['App']['GetGenreStats'](arg1);
}

export function GetLastScanFailure(arg1) {
  return window['go']['main']['App']['GetLastScanFailure'](arg1);
}

export function GetLastScanTask(arg1) {
  return window['go']['main']['App']['GetLastScanTask'](arg1);
}

export function GetLibraries() {
  return window['go']['main']['App']['GetLibraries']();
}

export function GetMediaDetail(arg1) {
  return window['go']['main']['App']['GetMediaDetail'](arg1);
}

export function GetMediaDetailBundle(arg1) {
  return window['go']['main']['App']['GetMediaDetailBundle'](arg1);
}

export function GetMediaFiles(arg1) {
  return window['go']['main']['App']['GetMediaFiles'](arg1);
}

export function GetMediaList(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['GetMediaList'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetMediaListFiltered(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['GetMediaListFiltered'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function GetMediaPreviews(arg1) {
  return window['go']['main']['App']['GetMediaPreviews'](arg1);
}

export function GetMyRating(arg1) {
  return window['go']['main']['App']['GetMyRating'](arg1);
}

export function GetNFOEditorData(arg1) {
  return window['go']['main']['App']['GetNFOEditorData'](arg1);
}

export function GetPosterEditorState(arg1) {
  return window['go']['main']['App']['GetPosterEditorState'](arg1);
}

export function GetSeriesStats(arg1) {
  return window['go']['main']['App']['GetSeriesStats'](arg1);
}

export function GetThumbnailFailure(arg1) {
  return window['go']['main']['App']['GetThumbnailFailure'](arg1);
}

export function ListMyTags() {
  return window['go']['main']['App']['ListMyTags']();
}

export function MergeMyTags(arg1, arg2) {
  return window['go']['main']['App']['MergeMyTags'](arg1, arg2);
}

export function MoveMyTag(arg1, arg2) {
  return window['go']['main']['App']['MoveMyTag'](arg1, arg2);
}

export function OpenMediaFolder(arg1) {
  return window['go']['main']['App']['OpenMediaFolder'](arg1);
}

export function OpenNFO(arg1) {
  return window['go']['main']['App']['OpenNFO'](arg1);
}

export function PlayMedia(arg1, arg2) {
  return window['go']['main']['App']['PlayMedia'](arg1, arg2);
}

export function PlayRandomLibraryMedia(arg1) {
  return window['go']['main']['App']['PlayRandomLibraryMedia'](arg1);
}

export function PlayWithExternalPlayer(arg1) {
  return window['go']['main']['App']['PlayWithExternalPlayer'](arg1);
}

export function RenameMyTag(arg1, arg2) {
  return window['go']['main']['App']['RenameMyTag'](arg1, arg2);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RestartMedia(arg1, arg2) {
  return window['go']['main']['App']['RestartMedia'](arg1, arg2);
}

export function RestoreMediaPoster(arg1) {
  return window['go']['main']['App']['RestoreMediaPoster'](arg1);
}

export function RetryFailedScan(arg1) {
  return window['go']['main']['App']['RetryFailedScan'](arg1);
}

export function RetryThumbnailTask(arg1) {
  return window['go']['main']['App']['RetryThumbnailTask'](arg1);
}

export function SaveMediaPoster(arg1) {
  return window['go']['main']['App']['SaveMediaPoster'](arg1);
}

export function SaveNFOEditorData(arg1, arg2) {
  return window['go']['main']['App']['SaveNFOEditorData'](arg1, arg2);
}

export function ScanLibrary(arg1) {
  return window['go']['main']['App']['ScanLibrary'](arg1);
}

export function ScanLibraryWithMode(arg1, arg2) {
  return window['go']['main']['App']['ScanLibraryWithMode'](arg1, arg2);
}

export function SelectActorAvatarFile() {
  return window['go']['main']['App']['SelectActorAvatarFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectPosterImageFile() {
  return window['go']['main']['App']['SelectPosterImageFile']();
}

export function SelectProgram() {
  return window['go']['main']['App']['SelectProgram']();
}

export function SetActorAvatarFromFile(arg1, arg2) {
  return window['go']['main']['App']['SetActorAvatarFromFile'](arg1, arg2);
}

export function SetActorAvatarFromURL(arg1, arg2) {
  return window['go']['main']['App']['SetActorAvatarFromURL'](arg1, arg2);
}

export function SetMediaTags(arg1, arg2) {
  return window['go']['main']['App']['SetMediaTags'](arg1, arg2);
}

export function SetMyRating(arg1, arg2) {
  return window['go']['main']['App']['SetMyRating'](arg1, arg2);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function ToggleWatched(arg1) {
  return window['go']['main']['App']['ToggleWatched'](arg1);
}

export function UpdateDesktopSettings(arg1) {
  return window['go']['main']['App']['UpdateDesktopSettings'](arg1);
}

export function UpdateLibrary(arg1) {
  return window['go']['main']['App']['UpdateLibrary'](arg1);
}
